---
- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: server.packages
  when: server.packages is defined

- name: Configure timezone
  sudo: yes
  shell: timedatectl set-timezone {{server.timezone}}

- name: Configure locale
  sudo: yes
  shell: localectl set-locale LANG="{{server.locale}}" LC_CTYPE="{{server.lang}}"