---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- shell: hostname
  register: current_hostname

- name: Install MySQL Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: mysql.packages

- name: Update root password for all root accounts
  mysql_user: name=root host={{ item }}
              check_implicit_admin=yes
              password={{ mysql.root_password }}
              login_user=root
              login_password={{ mysql.root_password }}
  with_items:
    - "{{ current_hostname.stdout | lower }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }}
              state=absent
              login_user=root
              login_password={{ mysql.root_password }}
  with_items:
    - localhost
    - "{{ current_hostname.stdout | lower }}"

- name: Create databases
  mysql_db: name={{ item.database }}
            state=present
            collation=utf8_general_ci
            encoding=utf8
            login_user=root
            login_password={{ mysql.root_password }}
  with_items: mysql.databases

- name: Create users
  mysql_user: name={{ item.user }}
              password={{ item.password }}
              priv={{ item.database }}.*:ALL
              state=present
              login_user=root
              login_password={{ mysql.root_password }}
  with_items: mysql.databases

- name: Import dump
  mysql_db: name={{ item.database }}
            state=import
            login_user=root
            login_password={{ mysql.root_password }}
            target=/vagrant/db/{{ item.dump }}
  with_items: mysql.databases
  ignore_errors: true