---
server:
    install: '1'
    packages: [curl, wget, git, locate]
    timezone: Europe/Amsterdam
    locale: en_US.UTF-8
    lang: en_US
apache:
    install: '1'
    packages: [rewrite, vhost_alias, headers, expires, filter]
mysql:
    install: '1'
    root_password: 'root_pw'
    packages: [mysql-server, mysql-client, python-mysqldb]
    databases:
        - database: db_name
          user: db_username
          password: db_pw
          dump: db_dump.sql
php:
    install: '1'
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-mysql, php5-curl, php5-gd, php5-xdebug, php5-memcache, php5-memcached]
memcached:
    install: '1'
xdebug:
    install: '1'
composer:
    install: '1'
blackfire:
    install: '1'
    server_id: your_id
    server_token: your_token
phpmyadmin:
    install: '1'
app:
    install: '1'
