---
- name: ensure timezone is set in cli php.ini
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'

- name: enabling opcache cli
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp=';?opcache.enable_cli=\d'
              line='opcache.enable_cli=1'

- name: set error_reporting
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp='error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT'
              line='error_reporting = E_ALL'

- name: set display_errors
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp='display_errors = Off'
              line='display_errors = On'

- name: set upload_max_filesize
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp='upload_max_filesize = 2M'
              line='upload_max_filesize = 128M'

- name: set post_max_size
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp='post_max_size = 8M'
              line='post_max_size = 128M'

- name: set max_execution_time
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp='max_execution_time = 30'
              line='max_execution_time = 180'

- name: set max_input_time
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp='max_input_time = 60'
              line='max_input_time = 300'
