---
- name: Install xDebug
  sudo: yes
  apt: pkg=php5-xdebug state=latest
  notify: restart apache
  when: xdebug.install == "1"

- name: Config
  sudo: yes
  template: >
    src=xdebug.tpl
    dest=/etc/php5/{{ item }}/conf.d/60-xdebug.ini
  with_items: ['cli', 'apache2']
  notify: restart apache
  when: xdebug.install == "1"

- name: Install graphviz for webgrind
  sudo: yes
  apt: pkg=graphviz state=latest
  notify: restart apache
  when: xdebug.profiler == "1"

- name: Config profiler
  sudo: yes
  template: >
    src=xdebug-profiler.tpl
    dest=/etc/php5/{{ item }}/conf.d/70-xdebug.ini
  with_items: ['cli', 'apache2']
  notify: restart apache
  when: xdebug.profiler == "1"

- name: Add cron to remove old xdebug output files preventing running out of disk space
  sudo: yes
  cron: name="check dirs" minute="*/15" job="/usr/bin/find /tmp -maxdepth 1 -mmin +120 -type f -name "xdebug.out.*" -exec rm -f {} \; > /dev/null"
  when: xdebug.profiler == "1"
